/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorPrincipal;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import modelo.Contenedor;

/**
 *
 * @author nataliasabogalrada
 */
public class VentanaPrincipal extends javax.swing.JFrame implements ActionListener {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());
    JButton[][] botones;
    ControladorPrincipal controlador;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setLocationRelativeTo(this);
        this.controlador = new ControladorPrincipal();
        botones = new JButton[3][6];
        dibujarBotones();
        pintarBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Contenedores"));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dibujarBotones() {
        int separado = 30;
        int ancho = 50;
        int alto = 50;
        int texto = 1;
        int extraX = 50;
        int extraY = 50;
        for (int i = 0; i < botones.length; i++) {
            for (int j = 0; j < botones[i].length; j++) {
                botones[i][j] = new JButton();
                //setbounds (posX, posY, ancho, alto)

                botones[i][j].setBounds(
                        ancho * j + separado,
                        alto * i + separado,
                        ancho, alto);
                if (j == botones[i].length - 1) {
                    botones[i][j].setBounds(ancho * j + extraY, alto * i + separado, ancho, alto);

                }
                if (i == botones.length - 1) {
                    botones[i][j].setBounds(ancho * j + separado, alto * i + extraX, ancho, alto);
                }

                if (i == botones.length - 1 && j == botones[i].length - 1) {
                    botones[i][j].setBounds(ancho * j + extraX, alto * i + extraY, ancho, alto);
                }

                botones[i][j].setText(String.valueOf(texto));
                botones[i][j].addActionListener(this);  //este boton escuchara algo
                //(This) cuando hablan de this estan hablando de la clase actual
                panel.add(botones[i][j]);
                texto++;
            }
        }
    }

    private void pintarBotones() {
        for (int i = 0; i < botones.length; i++) {
            for (int j = 0; j < botones[i].length; j++) {
                Contenedor contenedor = controlador.entregarContenedor(i, j);
                if (contenedor.estaDeshabilitado()) {
                    botones[i][j].setBackground(Color.gray);
                } else if (contenedor.estaOcupado()) {
                    botones[i][j].setBackground(Color.blue);
                } else if (contenedor.estaDisponible()) {
                    botones[i][j].setBackground(Color.white);
                }
            }
        }
    }

    @Override

    public void actionPerformed(ActionEvent e) {
        for (int i = 0; i < botones.length; i++) {
            for (int j = 0; j < botones[i].length; j++) {
                if (e.getSource().equals(botones[i][j])) {
                    int fila = i;
                    int columna = j;
                    //Contenedor contenedor = controlador.entregarContenedor(fila, columna); ya no porque le vamos a mandar el ID
                    if (controlador.estaHabilitado(fila, columna)) {
                        VentanaInicialContenedores inicial = new VentanaInicialContenedores(fila, columna);
                        inicial.setVisible(true);
                        inicial.setLocationRelativeTo(null);
                        this.dispose();

                    } else if (controlador.estaAlquilada(fila, columna)) {
                        VentanaSeguridad seguridad = new VentanaSeguridad(fila, columna);
                        seguridad.setVisible(true);
                        seguridad.setLocationRelativeTo(null);
                        this.dispose();
                    } else {
                        VentanaDeshabilitarContenedor des = new VentanaDeshabilitarContenedor(fila, columna);
                        des.setLocationRelativeTo(null);
                        des.setVisible(true);
                        this.dispose();
                    }

                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
