/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorContenedor;
import modelo.Contenedor;

/**
 *
 * @author nataliasabogalrada
 */
public class VentanaInicialContenedores extends javax.swing.JFrame {

    int fila;
    int columna;

    /**
     * Creates new form VentanaInicialContenedores
     */
    public VentanaInicialContenedores(int fila, int columna) {
        initComponents();
        setLocationRelativeTo(this);
        this.fila = fila;
        this.columna = columna;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDeshabilitar = new javax.swing.JButton();
        btnAlquilar = new javax.swing.JButton();
        btnAtrasControlAsistencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDeshabilitar.setText("Deshabilitar");
        btnDeshabilitar.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                btnDeshabilitarComponentHidden(evt);
            }
        });
        btnDeshabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeshabilitarActionPerformed(evt);
            }
        });

        btnAlquilar.setText("Alquilar Contenedor");
        btnAlquilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlquilarActionPerformed(evt);
            }
        });

        btnAtrasControlAsistencia.setText("⤺");
        btnAtrasControlAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasControlAsistenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnDeshabilitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlquilar, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAtrasControlAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAtrasControlAsistencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlquilar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeshabilitar)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeshabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeshabilitarActionPerformed
        VentanaDeshabilitarContenedor des = new VentanaDeshabilitarContenedor(fila, columna);
        des.setVisible(true);
        des.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnDeshabilitarActionPerformed

    private void btnAlquilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlquilarActionPerformed
        VentanaAlquilerContenedor alquilar = new VentanaAlquilerContenedor(fila, columna);
        alquilar.setVisible(true);
        alquilar.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnAlquilarActionPerformed

    private void btnDeshabilitarComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnDeshabilitarComponentHidden

    }//GEN-LAST:event_btnDeshabilitarComponentHidden

    private void btnAtrasControlAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasControlAsistenciaActionPerformed
        VentanaPrincipal prin = new VentanaPrincipal();
        prin.setLocationRelativeTo(null);
        prin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasControlAsistenciaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlquilar;
    private javax.swing.JButton btnAtrasControlAsistencia;
    private javax.swing.JButton btnDeshabilitar;
    // End of variables declaration//GEN-END:variables
}
